export const formatDisplayMode = (mode: 'dry-run' | 'live'): string =>
  mode === 'live' ? 'Live dispatch' : 'Dry-run';

export const formatServiceName = (value: string): string => {
  const normalized = value.trim().toLowerCase();

  switch (normalized) {
    case 'sonarr':
      return 'Sonarr';
    case 'radarr':
      return 'Radarr';
    case 'prowlarr':
      return 'Prowlarr';
    case 'transmission':
      return 'Transmission';
    case 'scheduler':
      return 'Scheduler';
    default:
      return normalized
        .split(/[\s_-]+/)
        .filter(Boolean)
        .map((part) => `${part[0]?.toUpperCase() ?? ''}${part.slice(1)}`)
        .join(' ');
  }
};

export const formatConfigSourceLabel = (value: string): string => {
  const normalized = value.trim().toLowerCase();

  switch (normalized) {
    case 'env':
      return 'Environment variable';
    case 'persisted':
      return 'Saved in app';
    case 'config':
      return 'Config file';
    case 'generated':
      return 'Generated by app';
    case 'missing':
      return 'Not configured';
    case 'none':
      return 'Not used';
    default:
      return formatServiceName(value);
  }
};

export const formatRunTypeLabel = (value: string): string =>
  value
    .replaceAll('_', ' ')
    .split(' ')
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase() ?? ''}${part.slice(1)}`)
    .join(' ');

export const formatShortRunId = (value: string | null): string => {
  if (!value) {
    return 'n/a';
  }

  const parts = value.split('_');
  const lastPart = parts.at(-1) ?? value;

  if (lastPart.length <= 8) {
    return value;
  }

  const prefix = parts.length > 1 ? `${parts.slice(0, -1).join(' ')} · ` : '';

  return `${prefix}${lastPart.slice(-8)}`;
};

const REASON_CODE_LABELS: Record<string, string> = {
  ELIGIBLE_MISSING_RECENT: 'Missing - recent - eligible for search',
  ELIGIBLE_MISSING_BACKLOG: 'Missing - backlog - eligible for search',
  ELIGIBLE_CUTOFF_RECENT: 'Cutoff unmet - recent - eligible for search',
  ELIGIBLE_CUTOFF_BACKLOG: 'Cutoff unmet - backlog - eligible for search',
  SKIP_UNMONITORED: 'Skipped - item is not monitored',
  SKIP_UNRELEASED: 'Skipped - item has not released yet',
  SKIP_IGNORED_STATE: 'Skipped - item is currently ignored',
  SKIP_IN_QUEUE: 'Skipped - already queued in Arr',
  SKIP_ITEM_SUPPRESSED: 'Skipped - item is currently suppressed',
  SKIP_RELEASE_SUPPRESSED: 'Skipped - release is suppressed',
  SKIP_COOLDOWN_ACTIVE: 'Skipped - retry cooldown is active',
  SKIP_GLOBAL_PANIC_DISABLE: 'Skipped - global dispatch panic switch is on',
  SKIP_GLOBAL_SEARCH_BLOCKED: 'Skipped - global search block is active',
  SKIP_APP_UNAVAILABLE: 'Skipped - app is unavailable',
  SKIP_GLOBAL_BUDGET_EXHAUSTED: 'Skipped - global dispatch budget is exhausted',
  SKIP_APP_BUDGET_EXHAUSTED: 'Skipped - app dispatch budget is exhausted',
  SKIP_DRY_RUN_ONLY: 'Skipped - dry-run only',
  TX_ERROR_REMOVE: 'Removed - Transmission reported an error',
  TX_STALLED_REMOVE: 'Removed - stalled download',
  TX_LOOP_REPEAT_RELEASE: 'Removed - repeated bad release loop',
  TX_DANGEROUS_DOWNLOAD_REMOVE: 'Removed - dangerous file type',
  TX_NOT_UPGRADE_REMOVE: 'Removed - not an upgrade',
  TX_NO_ACTION: 'No action taken',
};

export const formatReasonCodeLabel = (reasonCode: string): string =>
  REASON_CODE_LABELS[reasonCode] ?? formatServiceName(reasonCode.replaceAll('_', ' '));
